# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

# Optionally set the version of Python and requirements
python:
  version: 3.11
  install:
    - requirements: requirements.txt
    # If your project needs a specific setup.py call
    #- method: setuptools
    # If your documentation needs additional dependencies
    - requirements: docs/requirements.txt

# Formats: htmlzip, pdf, epub
formats:
  - htmlzip
  - pdf
  - epub

# Add build environments
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"

# Optionally configure MkDocs
# mkdocs:
    configuration: mkdocs.yml
#   fail_on_warning: false

# Optionally declare the version of this config file
# version: 2
